"""add business id to product

Revision ID: a659545be25b
Revises: 
Create Date: 2025-11-11 21:27:41.491841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a659545be25b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('business_id_fk', 'business', ['business_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('business_id_fk', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
